/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DatafetchingImport } from './routes/data_fetching'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DatafetchingRoute = DatafetchingImport.update({
  id: '/data_fetching',
  path: '/data_fetching',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/data_fetching': {
      id: '/data_fetching'
      path: '/data_fetching'
      fullPath: '/data_fetching'
      preLoaderRoute: typeof DatafetchingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/data_fetching': typeof DatafetchingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/data_fetching': typeof DatafetchingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/data_fetching': typeof DatafetchingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data_fetching'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data_fetching'
  id: '__root__' | '/' | '/data_fetching'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DatafetchingRoute: typeof DatafetchingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DatafetchingRoute: DatafetchingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/data_fetching"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/data_fetching": {
      "filePath": "data_fetching.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
